<?php

namespace Gelim\EMConfig\Facades;
/**
 * @method static add($scope, $key, $value)
 */
class EMConfigSet extends \Illuminate\Support\Facades\Facade
{
    protected static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return "emconfig-configset-manager";
    }
}
